### ISSUE TITLE
Advection seems deactivated in Lateral advection diffusion example

### ISSUE THREAD

**Issue by jsasaki-utokyo** [pmlmodelling/pylag#144]
I am trying to replicate the Lateral advection diffusion example. The analytical solution works well but the particle tracking results show no advection. Could you help?

**Comment by jimc101** [comment]
Hi - sorry for the slow reply. Please can you provide more details about your setup? Did you install PyLag using Conda? And the dependencies for running the notebooks from conda-forge? I just did a clean install of PyLag and reran that notebook. It failed due to issue #147, which I have just fixed. After doing this, the notebook executes without error for me and the three animations work. However, from your message, I don't think this was your problem.

**Comment by jsasaki-utokyo** [comment]
Thanks. Yes, I installed it using conda.
First, creating **environment.yaml** containing below:
```
name: pylag
dependencies:
  - scipy=1.11.4
```

Then I installed as follows:
```bash
conda config --prepend channels conda-forge
conda config --prepend channels JimClark
conda create -n pylag python=3.11
conda activate pylag
conda env update --file environment.yaml
conda install -n pylag -c JimClark pylag
```

**Comment by jimc101** [comment]
And did you install all the [dependencies](https://pylag.readthedocs.io/en/latest/install/installation.html#building-the-docs) PyLag needs to run the examples?

**Comment by jsasaki-utokyo** [comment]
I did not install the packages listed in [Building the Docs](https://pylag.readthedocs.io/en/latest/install/installation.html#building-the-docs) or the packages listed below it as I thought that the codes in [Examples](https://pylag.readthedocs.io/en/latest/examples/index.html) would work without installing them.
There were no import errors; but the plot did not reflect the advection.
[Background theory](https://pylag.readthedocs.io/en/latest/examples/lateral_adv_diff_analytic.html#Background-theory) worked like pylag1.mp4; however, [Running the particle tracking model](https://pylag.readthedocs.io/en/latest/examples/lateral_adv_diff_analytic.html#Running-the-particle-tracking-model) did not reflect the advection like pylag2.mp4 and pylag3.mp4 [here](https://drive.google.com/drive/u/0/folders/1f9_Im7OPsMut_gRztazxvYXvcc3-WNyQ).

The list of installed packages is shown [here](https://docs.google.com/document/d/13_3mhZgvTb5JB8_ggPC43VQszY9MDZRMvhS7jxq5_xU/edit).

**Comment by jimc101** [comment]
Hi - are you still struggling with this? I would be interested to know whether installing PyLag and the dependencies needed to build the docs fixed your problem?

**Comment by jsasaki-utokyo** [comment]
Yes, I'm still struggling; advection in [Lateral advection and diffusion](https://pylag.readthedocs.io/en/latest/examples/lateral_adv_diff_analytic.html#Lateral-advection-and-diffusion) still does not work.
Following [Installation using Conda](https://pylag.readthedocs.io/en/latest/install/installation.html#installation-using-conda), I installed in the pylag virtual environment as follows:

```bash
conda install -c JimClark pylag
conda install sphinx nbsphinx sphinx_rtd_theme sphinxcontrib-napoleon sphinx-copybutton
conda install jupyter jupyter_client ipykernel seapy cmocean matplotlib shapely cartopy
``` 

I could not install `PyQT-fit` as follows:
```bash
(pylag) teem@tpx1e2020:~$ conda install -c JimClark PyQT-fit
Channels:
 - JimClark
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE                                                                         failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pyqt-fit-1.3.0-py38hdf9c04a_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ pyqt-fit is not installable because there are no viable options
   ├─ pyqt-fit 1.3.0 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ pyqt-fit 1.4.1 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.11.* (labeled as 'pin-1')
```

Anyway, I tried [Examples](https://pylag.readthedocs.io/en/latest/examples/index.html) but it invoked an error associated with `scipy.interp`.

Then I locally installed (overwrote) pylag with `pip install .` following [Building from source](https://pylag.readthedocs.io/en/latest/install/installation.html#building-from-source), I locally installed (overwrite) pylag.

Pylag works but still advection does not appear in the example of [Lateral advection and diffusion].

**Comment by jimc101** [comment]
Yes, the `scipy.interp` problem (see #147 ) is fixed on Master but has not been folded into a new release yet. I will check on the PyQT-Fit issue in the fork I created; however, please note it is only needed to run one of the examples. I am afraid I am unsure why the animation isn't playing. The only other suggestion I have is to check you are excluding packages in ~/.local when starting up your conda env, as these can take precedence over packages in your environment and cause problems.

**Comment by jsasaki-utokyo** [comment]
Thanks. PyLag works well in actual applications with FVCOM outputs.

**Comment by jsasaki-utokyo** [comment]
A collaborator from a consulting company resolved the problem by activating ocean currents just before the data reader.

```Python
# Activating ocean currents
config.add_section("OCEAN_DATA")
config.set("OCEAN_DATA", "name", "dummy")

# The data reader
data_reader = MockVelocityEddyDiffusivityDataReader()
```
