### ISSUE TITLE
PackagesNotFoundError: pylag

### ISSUE THREAD

**Issue by yairsuari** [pmlmodelling/pylag#149]
**Sorry, this is probably a noob error, but I cant install pylag
I am on windows11 but I use the conda installation so I think I should be fine?
here is what I did (and went well):**

conda config --prepend channels conda-forge
conda config --prepend channels JimClark
conda create -n pylag python=3.11
conda activate pylag

**and then when running**
conda install -n pylag -c JimClark pylag

**I got**
PackagesNotFoundError: The following packages are not available from current channels:

  - pylag

**To be sure I tried conda search pylag
and again got**

PackagesNotFoundError:

**What am I missing here?**

**Comment by jimc101** [comment]
Sorry - support for Windows has not been implemented and there are no plans at present to add support for it. Do you have Windows Subsystem for Linux installed? If so, you could try running PyLag using it.

**Comment by yairsuari** [comment]
Thank you!
I think I will go to virtual machine
Yair

בתאריך יום ה׳, 20 ביוני 2024, 12:38, מאת Jim Clark ‏<
***@***.***>:

**Comment by jimc101** [comment]
Okay - good luck with the VM. I will close this issue now.
