### ISSUE TITLE
Fails for reverse time starting at 00 hours

### ISSUE THREAD

**Issue by akurekin** [pmlmodelling/pylag#165]
It works for
start_datetime = 2022-03-08 23:00:00
end_datetime = 2022-03-08 00:00:00

And also works for
start_datetime = 2022-03-09 01:00:00
end_datetime = 2022-03-08 00:00:00

But it does not work for 
start_datetime = 2022-03-09 00:00:00
end_datetime = 2022-03-08 00:00:00

The log file shows an error:

11/19/2024 04:54:17 PM - pylag.file_reader - INFO - Found first initial data file /data/sthenno1/scratch/modop/Model/FVCOM_rosa/archive_output/aqua_v16_2022-03-08.nc.
11/19/2024 04:54:17 PM - pylag.file_reader - INFO - Found second initial data file /data/sthenno1/scratch/modop/Model/FVCOM_rosa/archive_output/aqua_v16_2022-03-09.nc.
11/19/2024 04:54:17 PM - pylag.file_reader - INFO - Opened first data file /data/sthenno1/scratch/modop/Model/FVCOM_rosa/archive_output/aqua_v16_2022-03-08.nc for reading.
11/19/2024 04:54:17 PM - pylag.file_reader - INFO - Opened second data file /data/sthenno1/scratch/modop/Model/FVCOM_rosa/archive_output/aqua_v16_2022-03-09.nc for reading.
11/19/2024 04:54:17 PM - pylag.file_reader - INFO - The provided time 0.0s lies outside of the range for which there exists input data: 0.0 to 86400.0s

**Comment by jimc101** [comment]
I confirm this is a bug. It has its origins in the last time point in a data file being repeated in the next data file. There is logic to handle this when forward tracking. However, it breaks when doing backtracking - as evidenced here.
